import type { Metadata } from "next";
import "./globals.css";
import { poppins } from "@/fonts/PoppinsFont";

export const metadata: Metadata = {
  title: "Alvaro Sosa",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`   ${poppins.variable}  antialiased `}>
        <div className="bg-gradient-to-t from-zinc-800 to-zinc-950 ">
          {children}
        </div>
      </body>
    </html>
  );
}
